### ISSUE TITLE
ModuleNotFoundError: No module named 'ipinfo'

### ISSUE THREAD

**Issue by bmadhumay** [PriyabrataNaskar/ip-tracker#1]
raceback (most recent call last):
  File "C:\Users\Yamac\Documents\GitHub\ip-tracker\eye.py", line 1, in <module>
    import ipinfo
ModuleNotFoundError: No module named 'ipinfo'
>>> 

Please add instruction in readme

**Comment by PriyabrataNaskar** [comment]
Install the library ipinfo. 
```pip install ipinfo```
 also create account in IPINFO website to get the access token.
